CREATE TABLE IF NOT EXISTS mpa (
    id integer PRIMARY KEY,
    name varchar
);

CREATE TABLE IF NOT EXISTS films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar,
    description text,
    release_date timestamp,
    duration integer,
    mpa integer references mpa(id)
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar,
    login varchar,
    name varchar,
    birthday timestamp
);

CREATE TABLE IF NOT EXISTS likes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer references users(id),
    film_id integer references films(id)
);

CREATE TABLE IF NOT EXISTS friends (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer references users(id),
    friend_id integer,
    status text
);

CREATE TABLE IF NOT EXISTS genres (
    id integer PRIMARY KEY,
    name varchar
);

CREATE TABLE IF NOT EXISTS genres_films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id integer references films(id),
    genre_id integer references genres(id)
);


